

INSERT INTO GROUPS (NAME) VALUES('Alpha');
INSERT INTO GROUPS (NAME) VALUES('Beta');

INSERT INTO SUBJECTS (TITLE) VALUES('MATH');
INSERT INTO SUBJECTS (TITLE) VALUES('ART');
INSERT INTO SUBJECTS (TITLE) VALUES('HISTORY');
INSERT INTO SUBJECTS (TITLE) VALUES('CHEMISTRY');
INSERT INTO SUBJECTS (TITLE) VALUES('PHYSICS');


INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, GROUP_ID) VALUES('Juan', 'Granados', 1);
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, GROUP_ID) VALUES('James', 'Hetfield', 1);
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, GROUP_ID) VALUES('Bruce', 'Wayne', 2);
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, GROUP_ID) VALUES('Tony', 'Stark', 2);

INSERT INTO MARKS (STUDENT_ID, SUBJECT_ID, DATE, MARK) VALUES(1, 1, CURRENT_TIMESTAMP, 9.8);
INSERT INTO MARKS (STUDENT_ID, SUBJECT_ID, DATE, MARK) VALUES(1, 5, CURRENT_TIMESTAMP, 10.0);

INSERT INTO SUBJECT_TEACHER (SUBJECT_ID, GROUP_ID, TEACHER_ID) VALUES(1, 1, 1);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID, GROUP_ID, TEACHER_ID) VALUES(1, 2, 1);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID, GROUP_ID, TEACHER_ID) VALUES(5, 1, 2);