

INSERT INTO GROUPS (ID,NAME) VALUES(1, 'Alpha');
INSERT INTO GROUPS (ID,NAME) VALUES(2, 'Beta');

INSERT INTO SUBJECTS (ID, TITLE) VALUES(1, 'MATH');
INSERT INTO SUBJECTS (ID, TITLE) VALUES(2, 'ART');
INSERT INTO SUBJECTS (ID, TITLE) VALUES(3, 'HISTORY');
INSERT INTO SUBJECTS (ID, TITLE) VALUES(4, 'CHEMISTRY');
INSERT INTO SUBJECTS (ID, TITLE) VALUES(5, 'PHYSICS');


--INSERT INTO STUDENTS (ID, FIRST_NAME, LAST_NAME, GROUP_ID) VALUES(1,'Juan', 'Granados', 1);
--INSERT INTO STUDENTS (ID, FIRST_NAME, LAST_NAME, GROUP_ID) VALUES(2,'James', 'Hetfield', 1);
--INSERT INTO STUDENTS (ID, FIRST_NAME, LAST_NAME, GROUP_ID) VALUES(3,'Bruce', 'Wayne', 2);
--INSERT INTO STUDENTS (ID, FIRST_NAME, LAST_NAME, GROUP_ID) VALUES(4,'Tony', 'Stark', 2);

--INSERT INTO MARKS (ID, STUDENT_ID, SUBJECT_ID, DATE, MARK) VALUES(1, 1, 1, CURRENT_TIMESTAMP, 9.8);
--INSERT INTO MARKS (ID, STUDENT_ID, SUBJECT_ID, DATE, MARK) VALUES(2, 1, 5, CURRENT_TIMESTAMP, 10.0);